### ISSUE TITLE
Compile with Arduino IDE 1.8.5 on Linux Mint not possible

### ISSUE THREAD

**Issue by PaulG4H** [Edzelf/ESP32-Radio#59]
after manualy fixing of missing files I run into the following issue:
<code>
Arduino: 1.8.5 (Linux), Board: "ESPDuino (ESP-13 Module), 80 MHz, 57600, 4M (3M SPIFFS)"

WARNING: library ESPmDNS claims to run on (esp32) architecture(s) and may be incompatible with your current board which runs on (esp8266) architecture(s).
In file included from /home/paul/Arduino/libraries/SD/src/utility/Sd2Card.h:26:0,
                 from /home/paul/Arduino/libraries/SD/src/utility/SdFat.h:29,
                 from /home/paul/Arduino/libraries/SD/src/SD.h:20,
                 from /home/paul/Arduino/MQTT_ESP32_Nextion_Internet_Radio_Alarm_Clock/MQTT_ESP32_Nextion_Internet_Radio_Alarm_Clock.ino:110:
/home/paul/Arduino/libraries/SD/src/utility/Sd2PinMap.h:510:2: error: #error Architecture or board not supported.
 #error Architecture or board not supported.

  ^
Multiple libraries were found for "PubSubClient.h"
 Used: /home/paul/Arduino/libraries/PubSubClient
 Not used: /home/paul/Arduino/libraries/CMMC_MQTT_Connector
Multiple libraries were found for "SD.h"
 Used: /home/paul/Arduino/libraries/SD
 Not used: /home/paul/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/SD
 Not used: /home/paul/arduino-1.8.5/libraries/SD
Multiple libraries were found for "ArduinoOTA.h"
 Used: /home/paul/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ArduinoOTA
 Not used: /home/paul/arduino-1.8.5/libraries/ArduinoOTA
Multiple libraries were found for "SPI.h"
 Used: /home/paul/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/SPI
 Not used: /home/paul/arduino-1.8.5/libraries/SPI
exit status 1
Error compiling for board ESPDuino (ESP-13 Module).

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
</code>

And yes I follow the instructions even here:
http://randomnerdtutorials.com/installing-the-esp32-board-in-arduino-ide-mac-and-linux-instructions/

Many thank's for your support in advance!
Paul

**Comment by NonaSuomy** [comment]
ESP-13 is not an esp32
